### ISSUE TITLE
Wow nice project and PCB

### ISSUE THREAD

**Issue by ldijkman** [gonzho000/chpc#1]
Wow nice project and PCB

question 
how did you make the foto comeup 
when i search on thrmostats
see https://github.com/topics/thermostat

like thermostats
https://github.com/ldijkman/ART-ESP32-Touch-TFT-Thermostat

**Comment by gonzho000** [comment]
Thank you, 

About your question: do you mean "with what device did you make photos" or "can you attach photos of upcoming external display" or something else?

**Comment by ldijkman** [comment]
hi

on the RIGHT side of your github page there are tags
if you click on a tag => then you get a topic search

your project showed a nice foto in the topic search
eye catching 
liked that and wondered how you did that

but i have found it
i have a foto also in topic search now
https://github.com/topics/diy-nest
https://github.com/topics/remeha

Thank you
greet luberth
from the netherlands

**Comment by gonzho000** [comment]
oh, i see.

i don't remember how i did it..

Have a good day!
